# Header
menu:
  首页: /
  存档: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: